FROM oven/bun:1-alpine

# RUN apk add --no-cache libc6-compat
WORKDIR /src

# Copy package files first to cache the 'bun install' step
COPY package.json bun.lockb* ./
RUN bun install

# Copy the rest of the project
# COPY . .

RUN bunx nuxi prepare
# Expose the Nuxt dev port
EXPOSE 3000

CMD ["bun", "run", "dev"]
