# --- Development Dockerfile ---
FROM golang:1.24-alpine

RUN apk add --no-cache git curl && \
    go install github.com/cosmtrek/air@latest


WORKDIR /app

COPY .. 

RUN go build -o main .

EXPOSE 8080

CMD ["air"]
