FROM golang:1.25-alpine

# Install git for fetching dependencies and 'air' for hot-reload
RUN apk add --no-cache git
RUN go install github.com/air-verse/air@latest

WORKDIR /app

# Copy dependency files first to leverage Docker cache
COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Run Air to watch for changes
CMD ["air"]


EXPOSE 8080
